# Generated by Django 4.2 on 2023-04-26 14:13

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('score_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', game.models.FourDigitIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('word', models.CharField(max_length=50)),
                ('score_value', models.IntegerField()),
            ],
        ),
    ]
