# Generated by Django 3.2.18 on 2023-04-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score_value',
            field=models.IntegerField(null=True),
        ),
    ]
