# Generated by Django 3.2.18 on 2023-04-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='name',
            new_name='user',
        ),
    ]
