# Generated by Django 3.2.18 on 2023-04-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_score_value'),
        ('user', '0002_rename_name_score_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
